config/routes.rb
Rails.application.routes.draw do
  resources :shipments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shipment.rb
class Shipment < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
  before_action :set_shipment, only: [:show, :edit, :update, :destroy]

	   def scrape_delnetconnect
		  require 'rubygems'
		  require 'nokogiri'
		  require 'open-uri'

		  page = Nokogiri::HTML(open('http://delnetconnect.com/Track.aspx?txtvalue=Track_byAwb&Query=%27mgwd6001025%27'))
		   entries=page.css('#gridvwBind')
           @entriesArray = []
           entries.each do|el|
             @entriesArray <<el.text 
		   end
	   end
 
  
  # GET /shipments
  # GET /shipments.json
  def index
    @shipments = Shipment.all
  end

  # GET /shipments/1
  # GET /shipments/1.json
  def show
  end

  # GET /shipments/new
  def new
    @shipment = Shipment.new
  end

  # GET /shipments/1/edit
 
 def edit
  end

  # POST /shipments
  # POST /shipments.json
  def create
    @shipment = Shipment.new(shipment_params)

    respond_to do |format|
      if @shipment.save
        format.html { redirect_to @shipment, notice: 'Shipment was successfully created.' }
        format.json { render :show, status: :created, location: @shipment }
      else
        format.html { render :new }
        format.json { render json: @shipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shipments/1
  # PATCH/PUT /shipments/1.json
  def update
    respond_to do |format|
      if @shipment.update(shipment_params)
        format.html { redirect_to @shipment, notice: 'Shipment was successfully updated.' }
        format.json { render :show, status: :ok, location: @shipment }
      else
        format.html { render :edit }
        format.json { render json: @shipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shipments/1
  # DELETE /shipments/1.json
  def destroy
    @shipment.destroy
    respond_to do |format|
      format.html { redirect_to shipments_url, notice: 'Shipment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shipment
      @shipment = Shipment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shipment_params
      params.require(:shipment).permit(:AwbNo, :Booking_Date, :Origin, :Destination, :Consignee, :RefNo, :Status, :LastUpdate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Status</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shipments/_form.html.erb
<%= form_with(model: shipment, local: true) do |form| %>
  <% if shipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shipment.errors.count, "error") %> prohibited this shipment from being saved:</h2>

      <ul>
      <% shipment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :AwbNo %>
    <%= form.text_field :AwbNo, id: :shipment_AwbNo %>
  </div>

  <div class="field">
    <%= form.label :Booking_Date %>
    <%= form.text_field :Booking_Date, id: :shipment_Booking_Date %>
  </div>

  <div class="field">
    <%= form.label :Origin %>
    <%= form.text_area :Origin, id: :shipment_Origin %>
  </div>

  <div class="field">
    <%= form.label :Destination %>
    <%= form.text_area :Destination, id: :shipment_Destination %>
  </div>

  <div class="field">
    <%= form.label :Consignee %>
    <%= form.text_area :Consignee, id: :shipment_Consignee %>
  </div>

  <div class="field">
    <%= form.label :RefNo %>
    <%= form.text_field :RefNo, id: :shipment_RefNo %>
  </div>

  <div class="field">
    <%= form.label :Status %>
    <%= form.text_area :Status, id: :shipment_Status %>
  </div>

  <div class="field">
    <%= form.label :LastUpdate %>
    <%= form.text_field :LastUpdate, id: :shipment_LastUpdate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shipments/edit.html.erb
<h1>Editing Shipment</h1>

<%= render 'form', shipment: @shipment %>

<%= link_to 'Show', @shipment %> |
<%= link_to 'Back', shipments_path %>

app/views/shipments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shipments</h1>

<table>
  <thead>
    <tr>
      <th>Awbno</th>
      <th>Booking date</th>
      <th>Origin</th>
      <th>Destination</th>
      <th>Consignee</th>
      <th>Refno</th>
      <th>Status</th>
      <th>Lastupdate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shipments.each do |shipment| %>
      <tr>
        <td><%= shipment.AwbNo %></td>
        <td><%= shipment.Booking_Date %></td>
        <td><%= shipment.Origin %></td>
        <td><%= shipment.Destination %></td>
        <td><%= shipment.Consignee %></td>
        <td><%= shipment.RefNo %></td>
        <td><%= shipment.Status %></td>
        <td><%= shipment.LastUpdate %></td>
        <td><%= link_to 'Show', shipment %></td>
        <td><%= link_to 'Edit', edit_shipment_path(shipment) %></td>
        <td><%= link_to 'Destroy', shipment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shipment', new_shipment_path %>

app/views/shipments/new.html.erb
<h1>New Shipment</h1>

<%= render 'form', shipment: @shipment %>

<%= link_to 'Back', shipments_path %>

app/views/shipments/scrape_delnetconnect.html.erb
<h1>Shipment Details</h1>
<% @entriesArray.each do |el| %>
  <p><%= el.txt %></p> 
<% end %>

app/views/shipments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Awbno:</strong>
  <%= @shipment.AwbNo %>
</p>

<p>
  <strong>Booking date:</strong>
  <%= @shipment.Booking_Date %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @shipment.Origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @shipment.Destination %>
</p>

<p>
  <strong>Consignee:</strong>
  <%= @shipment.Consignee %>
</p>

<p>
  <strong>Refno:</strong>
  <%= @shipment.RefNo %>
</p>

<p>
  <strong>Status:</strong>
  <%= @shipment.Status %>
</p>

<p>
  <strong>Lastupdate:</strong>
  <%= @shipment.LastUpdate %>
</p>

<%= link_to 'Edit', edit_shipment_path(@shipment) %> |
<%= link_to 'Back', shipments_path %>